import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "@/lib/query-provider"
import { Nav } from "@/components/Nav"
import { Theme } from '@radix-ui/themes'
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Nav />
        <div className="p-4 lg:px-48">
          <Theme appearance="light">
            <Providers>
              {children}
            </Providers>
          </Theme>
        </div>
      </body>
    </html>
  )
}
