import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "@/lib/query-provider"
import { GlobalNav } from "@/components/GlobalNav"
import { Theme } from '@radix-ui/themes'
import "./globals.css"
import { ThemeProvider } from "../lib/theme-provider"
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Theme appearance="light">
              <GlobalNav />
              <div className="p-2 lg:py-6 lg:px-12">
                {children}
              </div>
              <ToastContainer />
            </Theme>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
